Repository ITDA-project/client, pull requests merged in 2025-04, with the labels that each got.

#42 ✨[feature] 로그인, 회원가입 연결
  src/.App.js.swp
  src/App.js
  src/components/RequireAuth.js
  src/contexts/AuthContext.js
  src/contexts/User.js
  src/navigations/Applicaton.js
  src/navigations/Auth.js
  src/navigations/Home.js
  src/navigations/Main.js
  src/navigations/index.js
  src/screens/Chat.js
  src/screens/CreatePost.js
  src/screens/MyPage.js
  src/screens/Profile.js
  src/screens/ReviewForm.js
  src/screens/SigninWithEmail.js
  src/screens/Signup.js
  src/screens/SignupDone.js
  src/screens/index.js
Labels: ✨feat

#43 ✨[Feature}게시글 수정 화면
  src/navigations/Main.js
  src/screens/CreatePost.js
  src/screens/EditPost.js
  src/screens/MainPage.js
  src/screens/MyPostDetail.js
  src/screens/PostDetail.js
  src/screens/index.js
Labels: ✨feat

#46 ✨[feature] 화면 연결
  .gitignore
  android/app/src/main/AndroidManifest.xml
  android/gradlew
  build/reports/configuration-cache/3msxx7llwqba0395kt9p6r0o7/2uiqj1blwh5q4psqk202jbc7p/configuration-cache-report.html
  build/reports/configuration-cache/dyn8oiyr21d67nfllt69wm4w5/aebhmusr3vm9659tbzio5gj5q/configuration-cache-report.html
  build/reports/problems/problems-report.html
  ios/Podfile.lock
  package-lock.json
  package.json
  src/components/RequireAuth.js
  src/contexts/AuthContext.js
  src/contexts/index.js
  src/hooks/useRequireLogin.js
  src/navigations/Home.js
  src/navigations/Main.js
  src/screens/AllPosts.js
  src/screens/Chat.js
  src/screens/MyPostDetail.js
  src/screens/PostDetail.js
  src/screens/Signin.js
  src/screens/SigninWithEmail.js
  src/screens/Signup.js
  src/setupProxy.js
  src/utils.js
Labels: ✨feat

#54 ✨[Feature] 비밀번호 찾기 화면 백 연결
  .gitignore
  android/app/src/main/AndroidManifest.xml
  android/gradlew
  build/reports/configuration-cache/3msxx7llwqba0395kt9p6r0o7/2uiqj1blwh5q4psqk202jbc7p/configuration-cache-report.html
  build/reports/configuration-cache/dyn8oiyr21d67nfllt69wm4w5/aebhmusr3vm9659tbzio5gj5q/configuration-cache-report.html
  build/reports/problems/problems-report.html
  ios/Podfile.lock
  package-lock.json
  package.json
  src/components/AlertModal.js
  src/components/RequireAuth.js
  src/components/index.js
  src/contexts/AuthContext.js
  src/contexts/index.js
  src/hooks/useRequireLogin.js
  src/navigations/Home.js
  src/navigations/Main.js
  src/screens/AllPosts.js
  src/screens/Chat.js
  src/screens/FindPw.js
  src/screens/MainPage.js
  src/screens/MyPostDetail.js
  src/screens/PostDetail.js
  src/screens/Search.js
  src/screens/Signin.js
  src/screens/SigninWithEmail.js
  src/screens/Signup.js
  src/setupProxy.js
  src/utils.js
Labels: ✨feat

#55 Feature/find pw connect
  src/components/AlertModal.js
  src/components/index.js
  src/contexts/AuthContext.js
  src/screens/FindPw.js
  src/screens/SigninWithEmail.js
Labels: ✨feat

#52 ✨[Feature] 공개프로필 연결
  package-lock.json
  package.json
  src/navigations/Main.js
  src/screens/PostDetail.js
  src/screens/PublicProfile.js
Labels: ✨feat

#58 ✨[feature] 로그아웃 연결
  src/contexts/AuthContext.js
  src/screens/Profile.js
  src/screens/Signin.js
  src/screens/SigninWithEmail.js
Labels: ✨feat

#62 ✨[feature] access token 재발급
  package-lock.json
  package.json
  src/api/api.js
  src/api/index.js
  src/contexts/AuthContext.js
  src/navigations/index.js
  src/screens/FindPw.js
  src/screens/SigninWithEmail.js
  src/screens/Signup.js
  src/utils.js
  src/utils/auth.js
  src/utils/index.js
  src/utils/utils.js
Labels: ✨feat

#60 ✨[feature] 메인,전체글 백연결
  src/screens/AllPosts.js
  src/screens/MainPage.js
Labels: ✨feat

#64 🐞[bugfix] 중복 이메일 경고 띄우기
  src/screens/Signin.js
  src/screens/Signup.js
Labels: 🐞bugfix

#66 ✨[Feature]게시글 상세보기 백연결
  src/screens/MyPostDetail.js
  src/screens/PostDetail.js
Labels: ✨feat

#69 ✨[feature] 게시글 생성 백연결
  src/screens/CreatePost.js
Labels: ✨feat

#70 ✨[Feature]마이페이지 백연결
  src/hooks/useRequireLogin.js
  src/navigations/Main.js
  src/screens/CreatePost.js
  src/screens/MainPage.js
  src/screens/MyPage.js
Labels: ✨feat, 🐞bugfix

#73 ✨[Feature] 검색 화면 백연결
  src/screens/Search.js
Labels: ✨feat

#75 ✨[Feature] 채팅 화면 구현
  src/navigations/Home.js
  src/navigations/Main.js
  src/screens/Chat.js
  src/screens/ChatList.js
  src/screens/CreatePost.js
  src/screens/EditPost.js
  src/screens/MyPostDetail.js
  src/screens/PostDetail.js
  src/screens/index.js
Labels: ✨feat
