Repository ITDA-project/client, pull requests merged in 2025-07, with the labels that each got.

#107 🐞[bugfix] 게시글 생성 후 뒤로가기 시 생성 페이지로 돌아가는 문제 해결
  src/screens/CreatePost.js
Labels: 🐞bugfix

#111 🐞[bugfix] 채팅시 프로필사진 안 보이는 문제 해결
  src/screens/Chat.js
Labels: 🐞bugfix

#113 ✨[Feature] 채팅+알림 안 읽은 수 표시
  src/navigations/Home.js
  src/screens/Chat.js
  src/screens/ChatList.js
  src/screens/Notifications.js
Labels: ✨feat

#115 🎨[Style] 게시글 생성 버튼 & 포커스 수정
  src/navigations/Home.js
  src/screens/ChatList.js
  src/screens/CreatePost.js
  src/screens/Notifications.js
Labels: 🎨style

#117 🐞[bugfix] 신청서 수락//거절 시 발생하는 문제 수정
  src/screens/ApplicationDecision.js
  src/screens/ApplicationList.js
  src/screens/SignupDone.js
Labels: 🐞bugfix

#118 ✨[feature] 세션 이용 결제
  src/components/ChatModal.js
  src/contexts/AuthContext.js
  src/screens/ApplicationList.js
  src/screens/Chat.js
  src/screens/EditProfile.js
  src/screens/MyPage.js
  src/screens/MyPostDetail.js
  src/screens/Notifications.js
  src/screens/PaymentScreen.js
  src/screens/PostDetail.js
  src/screens/Profile.js
  src/screens/PublicProfile.js
  src/utils/utils.js
Labels: ✨feat, 🎨style
