Repository ITDA-project/client, pull requests merged in 2025-05, with the labels that each got.

#76 Test
  src/contexts/AuthContext.js
  src/screens/CreatePost.js
  src/screens/MyPage.js
  src/screens/MyPostDetail.js
  src/screens/PostDetail.js
Labels: ✨feat, 🐞bugfix

#77 🐞[Bugfix] currentUserid 추출 수정, 변수명 수정
  src/screens/AllPosts.js
  src/screens/MainPage.js
  src/screens/MyPage.js
Labels: 🐞bugfix

#79 ✨[Feature] 알림 화면 구현
  src/screens/AllPosts.js
  src/screens/Notifications.js
Labels: ✨feat, ♻️refactor

#80 Bugfix/login, logout
  android/app/libs/oauth-5.10.0.aar
  android/app/src/main/res/drawable-hdpi/splashscreen_image.png
  android/app/src/main/res/drawable-mdpi/splashscreen_image.png
  android/app/src/main/res/drawable-xhdpi/splashscreen_image.png
  android/app/src/main/res/drawable-xxhdpi/splashscreen_image.png
  android/app/src/main/res/drawable-xxxhdpi/splashscreen_image.png
  android/app/src/main/res/drawable/splashscreen.xml
  android/build.gradle
  android/gradle/wrapper/gradle-wrapper.properties
  ios/moamoa.xcodeproj/project.pbxproj
  package-lock.json
  package.json
  src/contexts/AuthContext.js
  src/screens/CreatePost.js
  src/screens/DeleteAccount.js
  src/screens/MyPage.js
  src/screens/MyPostDetail.js
  src/screens/PostDetail.js
  src/screens/Profile.js
  src/screens/Signin.js
Labels: 🐞bugfix

#82 ✨[feature] 신청서 작성 백 연결
  src/screens/ApplicationForm.js
  src/screens/PostDetail.js
Labels: ✨feat

#86 ✨[Feature] 결제요청시 모달 화면 구현 / 🐞[BugFix] 프로필 사진 수정 오류
  android/app/src/main/AndroidManifest.xml
  app.json
  src/screens/EditProfile.js
  src/screens/Notifications.js
Labels: ✨feat, 🐞bugfix

#87 ✨[Feature] 모임 참여상태 여부 배지 추가
  src/screens/Chat.js
Labels: ✨feat

#93 ✨{Feature]안드로이드 알림 FCM 설정
  .gitignore
  package-lock.json
  package.json
  src/screens/Chat.js
Labels: ✨feat

#97 ✨[Feature] 모집기간 마감시 상세게시글 상태 변경
  src/screens/EditPost.js
  src/screens/MyPostDetail.js
  src/screens/PostDetail.js
Labels: ✨feat

#95 ✨[feature] 결제 백 연결
  android/app/src/main/AndroidManifest.xml
  package-lock.json
  package.json
  src/screens/Notifications.js
  src/screens/PaymentScreen.js
Labels: ✨feat

#98 ✨[feature] 채팅방 내 참가자, 주최자 여부에 따른 UI 분기
  src/screens/Chat.js
  src/screens/ChatList.js
  src/screens/CheckParticipants.js
Labels: ✨feat

#100 ✨[feature] 리뷰 화면 구현, 백 연결
  src/screens/Chat.js
  src/screens/ReviewForm.js
Labels: ✨feat

#103 🐞bugfix: 채팅방내 모임종료 후 뒤로가기 버튼 비활성화 문제 수정 외 2개
  src/screens/Chat.js
  src/screens/Notifications.js
  src/screens/Profile.js
Labels: ✨feat, 🐞bugfix, 🎨style
